name: MacOS

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: "==3.1.*"
          version: "6.8.0"
          host: mac
          target: desktop
          arch: clang_64

      - name: Configure CMake
        run: cmake --preset macos

      - name: Build library
        run: cmake --build --preset macos

      - name: Build tests
        run: cmake --build --preset macos-test

      - name: Run tests
        run: ctest --preset macos
